# This is a basic workflow to help you get started with Actions

name: Zip_Release

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it     
     - name: Zip Release
  # You may pin to the exact commit or the version.
  # uses: TheDoctor0/zip-release@a1afcab9c664c9976ac398fa831eac67bed1eb0e
       uses: TheDoctor0/zip-release@0.4.1
       with:
         # Filename for archive
         filename: 'release.zip'
         # Base path for archive files
         path: zip -r release.zip . -i davidlira19/Automated-Builds-CI-CD/tree/main
         # Working directory before zipping
         directory: /docs
         # List of excluded files / directories
         exclusions: '*.gitignore*'
         # Tool to use for archiving
        # type: zip
     - name: Upload Release
       uses: ncipollo/release-action@v1.8.3
       with:
        tag: ${{ startsWith(github.ref, 'refs/tags/Release') }}
        artifacts: "release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
